- name: Parse running-config data to collect source template information
  ansible.utils.cli_parse:
    command: show running-config | section ^interface
    parser:
      name: ansible.netcommon.native
      template_path: "{{ playbook_dir }}/roles/config_drift_role/templates/generate_structure.yml"
    set_fact: config_data

- name: Generate config lines to negate templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0777
  with_items:
    - {
        src: "{{ playbook_dir }}/roles/config_drift_role/templates/l2_config_template.j2",
        dest: "{{ playbook_dir }}/vars/interfaces_config.cfg",
      }

- name: Negate template configuration per interface
  cisco.ios.ios_config:
    src: "{{ playbook_dir }}/vars/interfaces_config.cfg"
    # backup: true
  # check_mode: true
